### ISSUE TITLE
complete codecademy "learn python"

### ISSUE THREAD

**Issue by ema-rose** [nesya04061919/wordnik-repl#2]
- [x] 1. python syntax
- [x] 2. strings and console
- [x] 3. conditionals and control flow
- [x] 4. function
  - [x] a.
  - [x] b.
- [x] 5. lists and dictionaries
  - [x] a.
  - [x] b.
- [x] 6. student becomes the teacher
  - [x] a.
- [x] 7. lists and functions
  - [x] a.
  - [x] b.
- [x] 8. loops
  - [x] a.
  - [x] b.
- [x] 9. exam statistics
  - [x] a.
- [x] 10. advanced topics in python
  - [x] a.
  - [x] b.
- [x] 11. introduction to classes
  - [x] a.
  - [x] b.
- [x] 12. file input and output
  - [x] a.

**Comment by ema-rose** [comment]
@michaeldayreads fyi this is my practice

**Comment by recursivelycurious** [comment]
Hurray! 🥇
